-- local status_ok, tree = pcall(require, "nvim-tree")
-- if not status_ok then
--     return
-- end

-- tree.setup({
--     open_on_setup = false,
--     open_on_setup_file = false,
--     hijack_unnamed_buffer_when_opening = false,
--     hijack_cursor = false,

--     view = {
--         adaptive_size = true,
--         float = {
--             enable = true,
--             -- quit_on_focus_loss = true,
--             -- open_win_config = {
--             --     relative = "editor",
--             --     border = "rounded",
--             --     width = 30,
--             --     height = 30,
--             --     row = 1,
--             --     col = 1
--             -- }
--         }
--     },
--     -- hijack_directories = {
--     --     enable = true,
--     --     auto_open = true
--     -- },
--     filters = {
--         dotfiles = false,
--         custom = {"^.git$"}
--     },
--     -- respect_buf_cwd = true,
--     -- update_focused_file = {
--     --     enable = true,
--     --     update_root = false,
--     --     ignore_list = {}
--     -- },
--     -- hijack_cursor = true,
--     diagnostics = {
--         enable = true
--     }
-- })
