require("user.plugins")
require("user.options")
require("user.keymaps")
-- require("user.coc")
-- require("user.luasnip")
-- require("user.cmp")
-- require("user.lsp")
require("user.null-ls")
-- require("user.autopairs")
require("user.lualine")
require("user.treesitter")
require("user.buffers")
require("user.comment")
require("user.telescope")
require("user.neogit")
require("user.glow")
require("user.delaytrain")
require("user.theme")
require("user.webicons")
require("user.alpha")
require("user.tree")
